version: '3.8'

services:
  app:
    build:
    ports:
      - "8080:8080"
    environment:
      - DB_HOST:db
      - DB_PORT: 5432
      - DB_USER: postgres
      - DB_PASSWORD: 12345
      - DB_NAME: postgres
    depends_on:
      - db

  db:
    build:
      context: db
      dockerfile: Dockerfile
    enviroment:
      POSTGRESS_USER: postgress
      POSTGRESS_PASSWORD: 12345
      POSTGRESS_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgress-data: /var/lib/postgresql/data

  volumes:
    postgress-data: 