package utils

type HTTPStatus struct {
	Code   int
	Reason string
}

var HTTPStatusMap = map[int]HTTPStatus{
	Continue:                      {Code: Continue, Reason: "Continue"},
	SwitchingProtocols:            {Code: SwitchingProtocols, Reason: "Switching Protocols"},
	Processing:                    {Code: Processing, Reason: "Processing"},
	OK:                            {Code: OK, Reason: "OK"},
	Created:                       {Code: Created, Reason: "Created"},
	Accepted:                      {Code: Accepted, Reason: "Accepted"},
	NonAuthoritativeInformation:   {Code: NonAuthoritativeInformation, Reason: "Non-Authoritative Information"},
	NoContent:                     {Code: NoContent, Reason: "No Content"},
	ResetContent:                  {Code: ResetContent, Reason: "Reset Content"},
	PartialContent:                {Code: PartialContent, Reason: "Partial Content"},
	MultiStatus:                   {Code: MultiStatus, Reason: "Multi-Status"},
	MultipleChoices:               {Code: MultipleChoices, Reason: "Multiple Choices"},
	MovedPermanently:              {Code: MovedPermanently, Reason: "Moved Permanently"},
	MovedTemporarily:              {Code: MovedTemporarily, Reason: "Moved Temporarily"},
	SeeOther:                      {Code: SeeOther, Reason: "See Other"},
	NotModified:                   {Code: NotModified, Reason: "Not Modified"},
	UseProxy:                      {Code: UseProxy, Reason: "Use Proxy"},
	TemporaryRedirect:             {Code: TemporaryRedirect, Reason: "Temporary Redirect"},
	PermanentRedirect:             {Code: PermanentRedirect, Reason: "Permanent Redirect"},
	BadRequest:                    {Code: BadRequest, Reason: "Bad Request"},
	Unauthorized:                  {Code: Unauthorized, Reason: "Unauthorized"},
	PaymentRequired:               {Code: PaymentRequired, Reason: "Payment Required"},
	Forbidden:                     {Code: Forbidden, Reason: "Forbidden"},
	NotFound:                      {Code: NotFound, Reason: "Not Found"},
	MethodNotAllowed:              {Code: MethodNotAllowed, Reason: "Method Not Allowed"},
	NotAcceptable:                 {Code: NotAcceptable, Reason: "Not Acceptable"},
	ProxyAuthenticationRequired:   {Code: ProxyAuthenticationRequired, Reason: "Proxy Authentication Required"},
	RequestTimeout:                {Code: RequestTimeout, Reason: "Request Timeout"},
	Conflict:                      {Code: Conflict, Reason: "Conflict"},
	Gone:                          {Code: Gone, Reason: "Gone"},
	LengthRequired:                {Code: LengthRequired, Reason: "Length Required"},
	PreconditionFailed:            {Code: PreconditionFailed, Reason: "Precondition Failed"},
	RequestEntityTooLarge:         {Code: RequestEntityTooLarge, Reason: "Request Entity Too Large"},
	RequestURITooLong:             {Code: RequestURITooLong, Reason: "Request URI Too Long"},
	UnsupportedMediaType:          {Code: UnsupportedMediaType, Reason: "Unsupported Media Type"},
	RequestedRangeNotSatisfiable:  {Code: RequestedRangeNotSatisfiable, Reason: "Requested Range Not Satisfiable"},
	ExpectationFailed:             {Code: ExpectationFailed, Reason: "Expectation Failed"},
	ImATeapot:                     {Code: ImATeapot, Reason: "I'm a teapot"},
	InsufficientSpaceOnResource:   {Code: InsufficientSpaceOnResource, Reason: "Insufficient Space On Resource"},
	MethodFailure:                 {Code: MethodFailure, Reason: "Method Failure"},
	MisdirectedRequest:            {Code: MisdirectedRequest, Reason: "Misdirected Request"},
	UnprocessableEntity:           {Code: UnprocessableEntity, Reason: "Unprocessable Entity"},
	Locked:                        {Code: Locked, Reason: "Locked"},
	FailedDependency:              {Code: FailedDependency, Reason: "Failed Dependency"},
	PreconditionRequired:          {Code: PreconditionRequired, Reason: "Precondition Required"},
	TooManyRequests:               {Code: TooManyRequests, Reason: "Too Many Requests"},
	RequestHeaderFieldsTooLarge:   {Code: RequestHeaderFieldsTooLarge, Reason: "Request Header Fields Too Large"},
	UnavailableForLegalReasons:    {Code: UnavailableForLegalReasons, Reason: "Unavailable For Legal Reasons"},
	InternalServerError:           {Code: InternalServerError, Reason: "Internal Server Error"},
	NotImplemented:                {Code: NotImplemented, Reason: "Not Implemented"},
	BadGateway:                    {Code: BadGateway, Reason: "Bad Gateway"},
	ServiceUnavailable:            {Code: ServiceUnavailable, Reason: "Service Unavailable"},
	GatewayTimeout:                {Code: GatewayTimeout, Reason: "Gateway Timeout"},
	HTTPVersionNotSupported:       {Code: HTTPVersionNotSupported, Reason: "HTTP Version Not Supported"},
	InsufficientStorage:           {Code: InsufficientStorage, Reason: "Insufficient Storage"},
	NetworkAuthenticationRequired: {Code: NetworkAuthenticationRequired, Reason: "Network Authentication Required"},
}
